---
id: 39
name: test_komiya_20220508
description: ''
user:
  id: 1
  email: admin@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: soql_file
    salesforce_connection:
      id: 3
      name: "[QA]data-catalog Salesforce"
    object: Case
    object_acquisition_method: soql
    api_version: '54.0'
    transfer_mode: type_interfence
    include_deleted_or_archived_records: false
    soql: SELECT Id, Subject FROM Case
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: Id
        type: string
      - name: Subject
        type: string
      quote: "\""
      escape: "\""
  out:
    type: bigquery
    bigquery_connection:
      id: 3
      name: test
    dataset: test_by_komiya
    table: localfile_test
    auto_create_dataset: false
    mode: append
    location: 
    open_timeout_sec: 300
    timeout_sec: 300
    send_timeout_sec: 300
    read_timeout_sec: 300
    retries: 5
    allow_quoted_newlines: true
    column_options: []
    template_table: ''
    time_partitioning:
      type: 
      field: ''
      expiration_ms: 
    custom_variables: []
  data_settings:
    columns:
    - name: Id
      src: Id
      default: ''
      type: string
    - name: Subject
      src: Subject
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
group: 
labels: []
job_schedules: []
triggers: []
notifications: []
